whatwg/spec-factory

- .pr-preview.json.template
Follows https://github.com/tabatkins/bikeshed/pull/1635.
> Use the new LS-PR status for PR previews

- factory.py
We currently don't yet support the HTML and Streams standards, yet `factory.json` still tries to update them.
> Don't update repos we don't yet support

- .editorconfig.template
- .pr-preview.json.template
- Makefile.template
I'm not sure about the default 2-space indents (vs. e.g. 4-space). The Python files in Encoding use 4-space, notably.
> Makefile and indentation fixes

- factory.py
This change fetches the `db.json` file that acts as the source of truth for the WHATWG repos from the master branch of [whatwg/sg](https://github.com/whatwg/sg), now that whatwg/sg#111 has been merged.
> Get db.json from sg's master branch

- .github/workflows/build.yml.template
- .github/workflows/deploy.yml.template
- .gitignore.template
- factory.py
Also remove any files that are part of the Travis setup.
Part of https://github.com/whatwg/meta/issues/173.
> Add GitHub Actions build.yml template

- factory.json
Its index.bs is indented 2 spaces, so this .editorconfig should be
synced manually until someone wants to change that.
> Exclude .editorconfig for console

- factory.py
This is the workaround recommended by the GitHub CLI maintainer:
https://github.com/whatwg/spec-factory/issues/19#issuecomment-651173812
Fixes https://github.com/whatwg/spec-factory/issues/19.
> Push branch to origin before invoking `gh pr create`

- README.md
The Streams standard was indeed handled in PR #15.
> Remove the mention of the Streams standard in the readme

- .github/workflows/build.yml.template
- factory.json
- factory.py
See https://github.com/heycam/webidl/pull/1018 for context.
Disclaimer: I haven't actually gotten `npm run pp-webidl -- --input index.html` to run locally yet.
> Handle Web IDL

- .github/workflows/build.yml.template
- factory.py
* Updates the actions themselves from v2 to v3.
* Updates the Node version from v14 to v16 (latest LTS).
* Updates the Python version from v3.8 to v3.10 (latest stable).
---
IMO we should merge this but not update all the specs. We can just let this ride along with any other future updates.
That's a bit risky because maybe there is some incompatibility between Python v3.8 and Python v3.10 that we would discover by doing this sooner. And then when we're trying to roll out some other more-important change, we get caught up figuring that out. But, in my estimation based on how we use Python and Node, that's unlikely.
> Update various versions used in GitHub Actions

- .github/workflows/build.yml.template
This ensures it is interpreted correctly and not as 3.1. See https://github.com/whatwg/webidl/pull/1156 for context.
> Quote Python version in .yml

- .github/workflows/build.yml.template
- factory.py
We could also do `ubuntu-latest` instead of choosing a specific Ubuntu version. I think that might be relatively safe?
I haven't tested the impact of Node v16 -> v18 or Python v3.10 -> v3.11 on our scripts, but I think it'll be fine.
> Update Ubuntu, Python, and Node versions

- PULL_REQUEST_TEMPLATE.md.template
To help people finish everything before pinging a PR for its final review.
This is based on some things Anne mentioned at https://matrix.to/#/!AGetWbsMpFPdSgUrbs:matrix.org/$eRoNst7XvM_u7lC03XyD44vEd8AwR029JvvrA7BDxXQ?via=matrix.org&via=mozilla.org&via=igalia.com. I'm not tied to any particular expression of these ideas and would be fine with being told that this isn't the right place to give these instructions.
> Add more PULL_REQUEST_TEMPLATE instructions

- .editorconfig.template
- factory.json
- factory.py
**WebIDL** uses 4 spaces for indentation in **Bikeshed** source files.
---
See <https://github.com/whatwg/webidl/pull/1040#issuecomment-939737611> by @annevk
> [webidl] Fix `indent_size` in `.editorconfig` for Bikeshed files

- factory.py
It defaults to the empty string so only when it is True do we need to override it.
> Cleanup build_with_node in factory.py

- factory.json
- factory.py
Instead of only modifying the template contents for a single specification, we were modifying them globally, causing erroneous output. This previously went unnoticed as we did not attempt to modify the template contents.
Additionally, exclude README.md from Web IDL for now as it has some custom things in there that need more consideration.
> Fix logic error in factory.py and exclude README.md from Web IDL for now

- .editorconfig.template
- factory.json
- factory.py
This includes support for overriding the .editorconfig max_line_length in the spec's Bikeshed file.
> Add URL Pattern standard

- .github/workflows/build.yml.template
This helps us move away from depending on the CSSWG API server, which is often broken.
> Install Bikeshed on CI

- .github/workflows/build.yml.template
- factory.py
This updates checkout, setup-python, and setup-node to their latest versions, which will remove some warnings on CI.
It also updates the Node.js version used from v18 to v20.
(It does not update Python from v3.11 to v3.12, since Bikeshed is only tested on v3.11 currently.)
---
I think these should all be pretty safe without needing to do any particular tests.
> Update GitHub Actions

- factory.json
closes https://github.com/whatwg/webidl/issues/1482
This PR, adds `package-lock.json` to the `.gitignore` file for WebIDL
> Ignore package-lock.json for WebIDL
